#!/usr/bin/env python3
"""Generate a port-shifted copy of the upstream docker-compose.deploy.yaml.

Reads:  stack/docker-compose.deploy.yaml          (upstream, untouched)
Writes: stack/docker-compose.local.yaml           (regenerated each run)

Shift is host-side only: every `host:container` mapping where the host port
matches `18\\d{3}` is rewritten to `${PORT_PREFIX}\\d{3}` with the same
trailing three digits. Container-side ports unchanged so internal Docker
DNS still resolves.

Also rewrites `localhost:18\\d{3}` patterns inside env-var URLs.

Configuration:
  PORT_PREFIX   two-digit prefix to substitute for 18. Default: 16.
                Source from config.env or pass via env.

Idempotent: rerun any time to regenerate from current upstream.
"""
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "stack" / "docker-compose.deploy.yaml"
DST = ROOT / "stack" / "docker-compose.local.yaml"

PORT_PREFIX = os.environ.get("PORT_PREFIX", "16")
if not re.fullmatch(r"\d{2}", PORT_PREFIX):
    sys.exit(f"PORT_PREFIX must be exactly 2 digits — got {PORT_PREFIX!r}")
if PORT_PREFIX == "18":
    sys.exit("PORT_PREFIX=18 is the upstream default — no shift needed; use docker-compose.deploy.yaml directly")

PORT_RE = re.compile(r'(?<![\d.])18(\d{3})(?=:\d)')
LOCALHOST_RE = re.compile(r'(localhost:)18(\d{3})(?!\d)')


def shift(text: str):
    n = 0

    def host_sub(m):
        nonlocal n
        n += 1
        return f"{PORT_PREFIX}{m.group(1)}"

    text = PORT_RE.sub(host_sub, text)

    def lh_sub(m):
        nonlocal n
        n += 1
        return f"{m.group(1)}{PORT_PREFIX}{m.group(2)}"

    text = LOCALHOST_RE.sub(lh_sub, text)
    return text, n


def main():
    if not SRC.exists():
        sys.exit(f"upstream compose missing: {SRC}")
    src = SRC.read_text()
    out, count = shift(src)
    if count == 0:
        sys.exit(f"no 18xxx host-port mappings found in {SRC}")
    header = (
        "# Auto-generated by scripts/gen-compose.py. Do not edit.\n"
        f"# Source: {SRC.relative_to(ROOT)}\n"
        f"# {count} host-port mappings shifted from 18xxx -> {PORT_PREFIX}xxx.\n"
        f"# Regenerate any time: PORT_PREFIX={PORT_PREFIX} python3 scripts/gen-compose.py\n\n"
    )
    DST.write_text(header + out)
    print(f"wrote {DST.relative_to(ROOT)}  ({count} ports -> {PORT_PREFIX}xxx)")


if __name__ == "__main__":
    main()
